# Generated by Django 5.2.8 on 2025-12-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('politics', 'Politics'), ('sports', 'Sports'), ('technology', 'Technology'), ('entertainment', 'Entertainment')], max_length=50)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='news_images/')),
            ],
        ),
    ]
