# Generated by Django 4.2.27 on 2026-01-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_remove_news_published_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_published'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
