# Generated by Django 4.2.27 on 2025-12-22 11:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
