# Generated by Django 4.2.27 on 2025-12-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_contactinformation_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
