# Generated by Django 4.2.27 on 2025-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_contactinformation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
