# Generated by Django 4.2.27 on 2026-01-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_memberprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberProfile',
            new_name='UserProfile',
        ),
    ]
