# Generated by Django 4.2.27 on 2026-01-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_memberprofile_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='MemberProfile',
        ),
    ]
