# Generated by Django 4.2.27 on 2026-01-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_userprofile_memberprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalinformation',
            name='school',
            field=models.CharField(blank=True, max_length=150, verbose_name='School/College'),
        ),
    ]
