# Generated by Django 4.2.27 on 2026-01-16 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_professionalinformation_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.BooleanField(default=True)),
                ('bio_visibility', models.BooleanField(default=True)),
                ('profile_picture_visibility', models.BooleanField(default=True)),
                ('contact_info_visibility', models.BooleanField(default=True)),
                ('email_visibility', models.BooleanField(default=True)),
                ('address_visibility', models.BooleanField(default=False)),
                ('visible_on_map', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
