# Generated by Django 4.2.27 on 2026-01-19 09:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_privacysettings_communicationpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacysettings',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_prefix',
            field=models.CharField(choices=[('+1', 'United States (+1)'), ('+7', 'Russia (+7)'), ('+20', 'Egypt (+20)'), ('+27', 'South Africa (+27)'), ('+30', 'Greece (+30)'), ('+31', 'Netherlands (+31)'), ('+32', 'Belgium (+32)'), ('+33', 'France (+33)'), ('+34', 'Spain (+34)'), ('+36', 'Hungary (+36)'), ('+39', 'Italy (+39)'), ('+40', 'Romania (+40)'), ('+41', 'Switzerland (+41)'), ('+43', 'Austria (+43)'), ('+44', 'United Kingdom (+44)'), ('+45', 'Denmark (+45)'), ('+46', 'Sweden (+46)'), ('+47', 'Norway (+47)'), ('+48', 'Poland (+48)'), ('+49', 'Germany (+49)'), ('+51', 'Peru (+51)'), ('+52', 'Mexico (+52)'), ('+53', 'Cuba (+53)'), ('+54', 'Argentina (+54)'), ('+55', 'Brazil (+55)'), ('+56', 'Chile (+56)'), ('+57', 'Colombia (+57)'), ('+58', 'Venezuela (+58)'), ('+60', 'Malaysia (+60)'), ('+61', 'Australia (+61)'), ('+62', 'Indonesia (+62)'), ('+63', 'Philippines (+63)'), ('+64', 'New Zealand (+64)'), ('+65', 'Singapore (+65)'), ('+66', 'Thailand (+66)'), ('+81', 'Japan (+81)'), ('+82', 'South Korea (+82)'), ('+84', 'Vietnam (+84)'), ('+86', 'China (+86)'), ('+90', 'Turkey (+90)'), ('+91', 'India (+91)'), ('+92', 'Pakistan (+92)'), ('+93', 'Afghanistan (+93)'), ('+94', 'Sri Lanka (+94)'), ('+95', 'Myanmar (+95)'), ('+98', 'Iran (+98)'), ('+211', 'South Sudan (+211)'), ('+212', 'Morocco (+212)'), ('+213', 'Algeria (+213)'), ('+216', 'Tunisia (+216)'), ('+218', 'Libya (+218)'), ('+220', 'Gambia (+220)'), ('+221', 'Senegal (+221)'), ('+222', 'Mauritania (+222)'), ('+223', 'Mali (+223)'), ('+224', 'Guinea (+224)'), ('+225', 'Ivory Coast (+225)'), ('+226', 'Burkina Faso (+226)'), ('+227', 'Niger (+227)'), ('+228', 'Togo (+228)'), ('+229', 'Benin (+229)'), ('+230', 'Mauritius (+230)'), ('+231', 'Liberia (+231)'), ('+232', 'Sierra Leone (+232)'), ('+233', 'Ghana (+233)'), ('+234', 'Nigeria (+234)'), ('+235', 'Chad (+235)'), ('+236', 'Central African Republic (+236)'), ('+237', 'Cameroon (+237)'), ('+238', 'Cape Verde (+238)'), ('+239', 'Sao Tome and Principe (+239)'), ('+240', 'Equatorial Guinea (+240)'), ('+241', 'Gabon (+241)'), ('+242', 'Republic of the Congo (+242)'), ('+243', 'DR Congo (+243)'), ('+244', 'Angola (+244)'), ('+245', 'Guinea-Bissau (+245)'), ('+246', 'British Indian Ocean Territory (+246)'), ('+247', 'Ascension Island (+247)'), ('+248', 'Seychelles (+248)'), ('+249', 'Sudan (+249)'), ('+250', 'Rwanda (+250)'), ('+251', 'Ethiopia (+251)'), ('+252', 'Somalia (+252)'), ('+253', 'Djibouti (+253)'), ('+254', 'Kenya (+254)'), ('+255', 'Tanzania (+255)'), ('+256', 'Uganda (+256)'), ('+257', 'Burundi (+257)'), ('+258', 'Mozambique (+258)'), ('+260', 'Zambia (+260)'), ('+261', 'Madagascar (+261)'), ('+262', 'Reunion (+262)'), ('+263', 'Zimbabwe (+263)'), ('+264', 'Namibia (+264)'), ('+265', 'Malawi (+265)'), ('+266', 'Lesotho (+266)'), ('+267', 'Botswana (+267)'), ('+268', 'Eswatini (+268)'), ('+269', 'Comoros (+269)'), ('+290', 'Saint Helena (+290)'), ('+291', 'Eritrea (+291)'), ('+297', 'Aruba (+297)'), ('+298', 'Faroe Islands (+298)'), ('+299', 'Greenland (+299)'), ('+350', 'Gibraltar (+350)'), ('+351', 'Portugal (+351)'), ('+352', 'Luxembourg (+352)'), ('+353', 'Ireland (+353)'), ('+354', 'Iceland (+354)'), ('+355', 'Albania (+355)'), ('+356', 'Malta (+356)'), ('+357', 'Cyprus (+357)'), ('+358', 'Finland (+358)'), ('+359', 'Bulgaria (+359)'), ('+370', 'Lithuania (+370)'), ('+371', 'Latvia (+371)'), ('+372', 'Estonia (+372)'), ('+373', 'Moldova (+373)'), ('+374', 'Armenia (+374)'), ('+375', 'Belarus (+375)'), ('+376', 'Andorra (+376)'), ('+377', 'Monaco (+377)'), ('+378', 'San Marino (+378)'), ('+379', 'Vatican (+379)'), ('+380', 'Ukraine (+380)'), ('+381', 'Serbia (+381)'), ('+382', 'Montenegro (+382)'), ('+383', 'Kosovo (+383)'), ('+385', 'Croatia (+385)'), ('+386', 'Slovenia (+386)'), ('+387', 'Bosnia and Herzegovina (+387)'), ('+389', 'North Macedonia (+389)'), ('+420', 'Czech Republic (+420)'), ('+421', 'Slovakia (+421)'), ('+423', 'Liechtenstein (+423)'), ('+500', 'Falkland Islands (+500)'), ('+501', 'Belize (+501)'), ('+502', 'Guatemala (+502)'), ('+503', 'El Salvador (+503)'), ('+504', 'Honduras (+504)'), ('+505', 'Nicaragua (+505)'), ('+506', 'Costa Rica (+506)'), ('+507', 'Panama (+507)'), ('+508', 'Saint Pierre and Miquelon (+508)'), ('+509', 'Haiti (+509)'), ('+590', 'Guadeloupe (+590)'), ('+591', 'Bolivia (+591)'), ('+592', 'Guyana (+592)'), ('+593', 'Ecuador (+593)'), ('+594', 'French Guiana (+594)'), ('+595', 'Paraguay (+595)'), ('+596', 'Martinique (+596)'), ('+597', 'Suriname (+597)'), ('+598', 'Uruguay (+598)'), ('+599', 'Curacao (+599)'), ('+670', 'East Timor (+670)'), ('+672', 'Antarctica (+672)'), ('+673', 'Brunei (+673)'), ('+674', 'Nauru (+674)'), ('+675', 'Papua New Guinea (+675)'), ('+676', 'Tonga (+676)'), ('+677', 'Solomon Islands (+677)'), ('+678', 'Vanuatu (+678)'), ('+679', 'Fiji (+679)'), ('+680', 'Palau (+680)'), ('+681', 'Wallis and Futuna (+681)'), ('+682', 'Cook Islands (+682)'), ('+683', 'Niue (+683)'), ('+685', 'Samoa (+685)'), ('+686', 'Kiribati (+686)'), ('+687', 'New Caledonia (+687)'), ('+688', 'Tuvalu (+688)'), ('+689', 'French Polynesia (+689)'), ('+690', 'Tokelau (+690)'), ('+691', 'Micronesia (+691)'), ('+692', 'Marshall Islands (+692)'), ('+850', 'North Korea (+850)'), ('+852', 'Hong Kong (+852)'), ('+853', 'Macau (+853)'), ('+855', 'Cambodia (+855)'), ('+856', 'Laos (+856)'), ('+880', 'Bangladesh (+880)'), ('+886', 'Taiwan (+886)'), ('+960', 'Maldives (+960)'), ('+961', 'Lebanon (+961)'), ('+962', 'Jordan (+962)'), ('+963', 'Syria (+963)'), ('+964', 'Iraq (+964)'), ('+965', 'Kuwait (+965)'), ('+966', 'Saudi Arabia (+966)'), ('+967', 'Yemen (+967)'), ('+968', 'Oman (+968)'), ('+970', 'Palestine (+970)'), ('+971', 'United Arab Emirates (+971)'), ('+972', 'Israel (+972)'), ('+973', 'Bahrain (+973)'), ('+974', 'Qatar (+974)'), ('+975', 'Bhutan (+975)'), ('+976', 'Mongolia (+976)'), ('+977', 'Nepal (+977)'), ('+992', 'Tajikistan (+992)'), ('+993', 'Turkmenistan (+993)'), ('+994', 'Azerbaijan (+994)'), ('+995', 'Georgia (+995)'), ('+996', 'Kyrgyzstan (+996)'), ('+998', 'Uzbekistan (+998)'), ('+1242', 'Bahamas (+1242)'), ('+1246', 'Barbados (+1246)'), ('+1264', 'Anguilla (+1264)'), ('+1268', 'Antigua and Barbuda (+1268)'), ('+1284', 'British Virgin Islands (+1284)'), ('+1340', 'U.S. Virgin Islands (+1340)'), ('+1345', 'Cayman Islands (+1345)'), ('+1441', 'Bermuda (+1441)'), ('+1473', 'Grenada (+1473)'), ('+1649', 'Turks and Caicos Islands (+1649)'), ('+1664', 'Montserrat (+1664)'), ('+1670', 'Northern Mariana Islands (+1670)'), ('+1671', 'Guam (+1671)'), ('+1684', 'American Samoa (+1684)'), ('+1758', 'Saint Lucia (+1758)'), ('+1767', 'Dominica (+1767)'), ('+1784', 'Saint Vincent and the Grenadines (+1784)'), ('+1787', 'Puerto Rico (+1787)'), ('+1809', 'Dominican Republic (+1809)'), ('+1868', 'Trinidad and Tobago (+1868)'), ('+1869', 'Saint Kitts and Nevis (+1869)'), ('+1876', 'Jamaica (+1876)')], default='+91', max_length=5),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='professionalinformation',
            name='school',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='CommunicationPreferences',
        ),
        migrations.DeleteModel(
            name='PrivacySettings',
        ),
    ]
