# Generated by Django 4.2.27 on 2026-01-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_userprofile_priority_userprofile_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='final_rank',
            field=models.IntegerField(default=0),
        ),
    ]
