# Generated by Django 4.2.27 on 2025-12-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='needrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='need_attachments/'),
        ),
        migrations.AddField(
            model_name='needrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('Medical', 'Medical'), ('Transport', 'Transport'), ('Food', 'Food'), ('Blood', 'Blood'), ('Accommodation', 'Accommodation'), ('Education', 'Education'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='needrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='need_images/'),
        ),
        migrations.AddField(
            model_name='needrequest',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='needrequest',
            name='urgency',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
    ]
