# Generated by Django 4.2.27 on 2025-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_service', '0002_needrequest_attachment_needrequest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='needrequest',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='needrequest',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
