# Generated by Django 4.2.27 on 2025-12-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_service', '0003_needrequest_latitude_needrequest_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='needrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
