# Generated by Django 4.2.27 on 2026-01-21 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community_service', '0004_alter_needrequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='needrequest',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
